import { EvidenceUnit } from './segmentation';
import { Finding } from './schema';

export type CoverageStatus = 'COVERED' | 'REVIEW_REQUIRED' | 'EXTRACTION_UNCERTAIN';

export interface CategoryCoverage {
    status: CoverageStatus;
    evidence_units_count: number;
    verified_findings_count: number;
    reason: string;
}

export const CRITICAL_CATEGORIES = [
    'ELIGIBILITY',
    'DATES_SUBMISSION',
    'TERMINATION',
    'LIABILITY_RISK',
    'INDEMNITY',
    'FINANCIAL_REQUIREMENTS',
    'PENALTIES_LIQUIDATED_DAMAGES',
    'EMD_BID_SECURITY',
    'PERFORMANCE_SECURITY',
    'EVALUATION_THRESHOLDS',
    'INSURANCE',
    'MANDATORY_DOCUMENTS'
] as const;

export type CriticalCategory = typeof CRITICAL_CATEGORIES[number];

// Keywords to associate Evidence Units or Findings with one of the 12 critical categories
const CATEGORY_LEXICON: Record<CriticalCategory, string[]> = {
    'ELIGIBILITY': ['eligibility', 'qualification', 'mandatory', 'minimum criteria', 'eligible bidder', 'experience'],
    'DATES_SUBMISSION': ['submission', 'deadline', 'due date', 'timeline', 'key dates', 'closing date', 'validity'],
    'TERMINATION': ['termination', 'terminate', 'convenience', 'default', 'suspend', 'cancel', 'breach'],
    'LIABILITY_RISK': ['liability', 'damages', 'consequential', 'indirect damages', 'liability cap', 'vicarious', 'loss'],
    'INDEMNITY': ['indemnity', 'indemnification', 'hold harmless', 'indemnify'],
    'FINANCIAL_REQUIREMENTS': ['turnover', 'net worth', 'financial capacity', 'financial turnover'],
    'PENALTIES_LIQUIDATED_DAMAGES': ['penalty', 'liquidated damages', 'sla', 'service level agreement', 'penalties'],
    'EMD_BID_SECURITY': ['emd', 'earnest money', 'bid security'],
    'PERFORMANCE_SECURITY': ['performance security', 'pbg', 'performance bank guarantee', 'security deposit'],
    'EVALUATION_THRESHOLDS': ['evaluation', 'scoring', 'weightage', 'qcbs', 'minimum qualifying', 'threshold', 'marks'],
    'INSURANCE': ['insurance', 'insured', 'policy'],
    'MANDATORY_DOCUMENTS': ['mandatory documents', 'certification', 'iso', 'format of proposal', 'upload']
};

/**
 * Assesses the coverage status for all critical categories.
 * 
 * Logic:
 * - COVERED: verified finding exists AND relevant evidence units were examined.
 * - REVIEW_REQUIRED: relevant evidence units exist, but no verified finding survived extraction/recovery.
 * - EXTRACTION_UNCERTAIN: insufficient candidate/evidence coverage to make a meaningful conclusion.
 * 
 * @param allUnits All Evidence Units generated by retrieval/segmentation
 * @param verifiedFindings All Findings that successfully passed extraction, verification, and recovery
 */
export function assessCriticalCoverage(
    allUnits: EvidenceUnit[],
    verifiedFindings: { finding: Finding }[]
): Record<CriticalCategory, CategoryCoverage> {
    
    const coverageReport = {} as Record<CriticalCategory, CategoryCoverage>;

    for (const cat of CRITICAL_CATEGORIES) {
        const keywords = CATEGORY_LEXICON[cat];

        // 1. Identify relevant evidence units
        const relevantUnits = allUnits.filter(u => {
            // Check if the unit's original category or trigger terms map to this sub-category
            if (u.category.toUpperCase() === cat) return true;
            if (u.trigger_terms && u.trigger_terms.some(t => keywords.some(k => t.toLowerCase().includes(k)))) return true;
            // Also check the source text just in case retrieval triggered on something else but this text is relevant
            if (u.source_text) {
                const textLow = u.source_text.toLowerCase();
                return keywords.some(k => textLow.includes(k));
            }
            return false;
        });

        // 2. Identify relevant verified findings
        const relevantFindings = verifiedFindings.filter(f => {
            const finding = f.finding;
            if (!finding) return false;
            if (finding.category.toUpperCase() === cat) return true;
            
            // Search finding text (title, fact, quotes)
            const searchText = [
                finding.title || '',
                finding.fact || '',
                ...(finding.quotes?.map(q => q.quote) || [])
            ].join(' ').toLowerCase();

            return keywords.some(k => searchText.includes(k));
        });

        const unitsCount = relevantUnits.length;
        const findingsCount = relevantFindings.length;

        let status: CoverageStatus;
        let reason = '';

        if (findingsCount > 0 && unitsCount > 0) {
            status = 'COVERED';
            reason = 'Verified finding(s) exist and evidence units were examined.';
        } else if (findingsCount > 0 && unitsCount === 0) {
            status = 'REVIEW_REQUIRED';
            reason = 'Verified finding exists but no explicit evidence units mapped to this category. Manual review recommended.';
        } else if (findingsCount === 0 && unitsCount > 0) {
            status = 'REVIEW_REQUIRED';
            reason = 'Relevant evidence units exist, but no verified finding survived extraction/recovery.';
        } else {
            // findingsCount === 0 && unitsCount === 0
            status = 'EXTRACTION_UNCERTAIN';
            reason = 'Insufficient candidate/evidence coverage to make a meaningful conclusion.';
        }

        coverageReport[cat] = {
            status,
            evidence_units_count: unitsCount,
            verified_findings_count: findingsCount,
            reason
        };
    }

    return coverageReport;
}
